# Generated by Django 5.2.6 on 2025-09-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to='products_videos'),
        ),
    ]
