# Generated by Django 5.2.6 on 2025-10-05 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_cartitem_wishlistitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserChoice',
        ),
    ]
