# Generated by Django 5.2.6 on 2025-10-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_delete_userchoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.CharField(default='black', max_length=20),
        ),
    ]
