# Generated by Django 5.2.6 on 2025-10-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
