# Generated by Django 5.2.6 on 2025-10-08 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productreview_reviewimage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together=set(),
        ),
    ]
