# Generated by Django 5.2.6 on 2025-10-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productreview_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
    ]
