# Generated by Django 5.2.7 on 2025-11-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_billingaddress_user_shippingaddress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='EPAYTEST', max_length=50),
        ),
    ]
