# Generated by Django 5.2.7 on 2025-11-05 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_product_code_paymentesewa_paymentstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentesewa',
            name='signature',
        ),
    ]
